### ISSUE TITLE
User configuration

### ISSUE THREAD

**Issue by dannypsnl** [kentookura/forester.nvim#12]
In the current code, the `--dir` option provides to forester is hardcoded in

https://github.com/kentookura/forester.nvim/blob/e61df39feb06ac0fc5b18baa3edaa519e2ee9ff9/lua/forester.lua#L12

Can we have a temporary configurable option for the plugin?

**Comment by kentookura** [comment]
I will add a config option to specify the value of `tree_dir`, but I won't add much lua code to handle lists of dirs and globs like `trees/*`. You talked briefly about config files in [this discussion](https://lists.sr.ht/~jonsterling/forester-discuss/%3CMiYmdynN4NegvqN4KrCurCZ4umQYbJw9JU0efHSS8dXNQl-NNK1NiUWJF_WAC0HSUAidXQCobkdGO1IxTk0DvjGqu9r2sVp6TCU6KaXO7WU%3D%40protonmail.com%3E), so when that feature is implemented, we will do something different (lsp)

**Comment by dannypsnl** [comment]
If tree_dir is a string, then forester can take it properly, just "trees1,tree2" and so on.

**Comment by kentookura** [comment]
That's as far as I'll get today but I invited you as a collaborator so you can push to that branch.

https://github.com/kentookura/forester.nvim/blob/4c080c7299d82ba02e082d5da23daf516076edd0/lua/forester.lua#L26-L41

**Comment by dannypsnl** [comment]
I find I don't understand the lazy configuration logic, do you have an example to config in lazy.nvim?

**Comment by kentookura** [comment]
I've had trouble with that too. I recommend looking at some of folke's plugins to see how he does it: https://github.com/folke

The gist of it is that this function get's called when the plugin is loaded:
https://github.com/kentookura/forester.nvim/blob/4c080c7299d82ba02e082d5da23daf516076edd0/lua/forester.lua#L29-L41

But it's not clear to me how to set "global state" that we can reference throughout the plugin. For instance, how can we get the current tree directory when calling `new_tree` without passing it as an argument? Because if we pass it as an argument, the keybinds would stop working I think.

Upon using forester.nvim a bit more, I think we need to think a bit more about how the plugin manages distinct forests.

What do you think about this workflow/design:

The plugin has global state, namely a list of forests with associated directories. Searching for tree titles and such should always search globally, but when creating, linking and transcluding trees, the plugin does it "locally", in the sense that it only considers prefixes of the forest that contains the tree of the current buffer.

https://github.com/ThePrimeagen/harpoon/tree/harpoon2

Harpoon is a plugin for quickly jumping between different projects, we could use it as a reference.

**Comment by kentookura** [comment]
We can use `vim.g` and other vim APIs

**Comment by dannypsnl** [comment]
It sounds would work.

**Comment by kentookura** [comment]
https://www.reddit.com/r/neovim/comments/pfu1jx/why_do_plugin_devs_prefer_setup_to_vimg_for/
https://www.reddit.com/r/neovim/comments/190y9j4/writing_a_lua_plugin_with_a_setup_function/

**Comment by kentookura** [comment]
Could you verify the branch works for you? I have it working set up like this:
```lua
  {
    "kentookura/forester.nvim",
    branch = "configure-tree-dir",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter" },
      { "nvim-telescope/telescope.nvim" },
      { "nvim-lua/plenary.nvim" },
    },
    opts = {
      forests = { "~/glade/notes", "~/forest" }, -- global forest config
      tree_dirs = { "trees", "test/trees", "notes", "doc" }, -- plugin will check if current directory contains these
      conceal = true,
    },
    config = function(opts)
      require("forester").setup(opts)
      vim.keymap.set("n", "<leader>n.", "<cmd>Forester browse<CR>", { silent = true })
      vim.keymap.set("n", "<leader>nn", "<cmd>Forester new<CR>", { silent = true })
      vim.keymap.set("i", "<C-t>", "<cmd>Forester transclude<CR>", { silent = true })
      vim.keymap.set("i", "<C-l>", "<cmd>Forester link<CR>", { silent = true })
    end,
  },
```

**Comment by dannypsnl** [comment]
Just tried, but there are some error like no parser for language forester.

**Comment by dannypsnl** [comment]
I figure it out, the config can work now.

**Comment by kentookura** [comment]
Great, will update the main branch today
